///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace mortfolioTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the mortfolioTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("10fd588b-a888-48de-adc1-35366bc89065")]
    public partial class mortfolioTestRepository : RepoGenBaseFolder
    {
        static mortfolioTestRepository instance = new mortfolioTestRepository();

        /// <summary>
        /// Gets the singleton class instance representing the mortfolioTestRepository element repository.
        /// </summary>
        [RepositoryFolder("10fd588b-a888-48de-adc1-35366bc89065")]
        public static mortfolioTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public mortfolioTestRepository() 
            : base("mortfolioTestRepository", "/", null, 0, false, "10fd588b-a888-48de-adc1-35366bc89065", ".\\RepositoryImages\\mortfolioTestRepository10fd588b.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("10fd588b-a888-48de-adc1-35366bc89065")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class mortfolioTestRepositoryFolders
    {
    }
#pragma warning restore 0436
}