///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace mortfolioTestLibrary
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("4354ee9d-2987-4edc-87a5-645c3443240a", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the mortfolioTestLibraryRepository repository.
        /// </summary>
        public static mortfolioTestLibraryRepository repo = mortfolioTestLibraryRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
            userName = "onur.ustunay";
            password = "14531071";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

        string _userName;

        /// <summary>
        /// Gets or sets the value of variable userName.
        /// </summary>
        [TestVariable("01da8c4e-c9b8-46a8-a00e-3c5f12372d94")]
        public string userName
        {
            get { return _userName; }
            set { _userName = value; }
        }

        string _password;

        /// <summary>
        /// Gets or sets the value of variable password.
        /// </summary>
        [TestVariable("0ff708a0-ff8d-4b13-bf73-9448e0172dab")]
        public string password
        {
            get { return _password; }
            set { _password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$userName' with focus on 'LoginPage.MainContentUserNameI'.", repo.LoginPage.MainContentUserNameIInfo, new RecordItemIndex(0));
            repo.LoginPage.MainContentUserNameI.PressKeys(userName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$password' with focus on 'LoginPage.MainContentTxtPKeyI'.", repo.LoginPage.MainContentTxtPKeyIInfo, new RecordItemIndex(1));
            repo.LoginPage.MainContentTxtPKeyI.PressKeys(password);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginPage.MainContentBtnOKCD' at 42;25.", repo.LoginPage.MainContentBtnOKCDInfo, new RecordItemIndex(2));
            repo.LoginPage.MainContentBtnOKCD.Click("42;25");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
