///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace mortfolioTestLibrary
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the mortfolioTestLibraryRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("5c61cc92-7ca1-4762-bf42-fe9c8b33118d")]
    public partial class mortfolioTestLibraryRepository : RepoGenBaseFolder
    {
        static mortfolioTestLibraryRepository instance = new mortfolioTestLibraryRepository();
        mortfolioTestLibraryRepositoryFolders.LoginPageAppFolder _loginpage;

        /// <summary>
        /// Gets the singleton class instance representing the mortfolioTestLibraryRepository element repository.
        /// </summary>
        [RepositoryFolder("5c61cc92-7ca1-4762-bf42-fe9c8b33118d")]
        public static mortfolioTestLibraryRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public mortfolioTestLibraryRepository() 
            : base("mortfolioTestLibraryRepository", "/", null, 0, false, "5c61cc92-7ca1-4762-bf42-fe9c8b33118d", ".\\RepositoryImages\\mortfolioTestLibraryRepository5c61cc92.rximgres")
        {
            _loginpage = new mortfolioTestLibraryRepositoryFolders.LoginPageAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5c61cc92-7ca1-4762-bf42-fe9c8b33118d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The LoginPage folder.
        /// </summary>
        [RepositoryFolder("45ae68e9-d80f-47fa-b911-fb57bac99e43")]
        public virtual mortfolioTestLibraryRepositoryFolders.LoginPageAppFolder LoginPage
        {
            get { return _loginpage; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class mortfolioTestLibraryRepositoryFolders
    {
        /// <summary>
        /// The LoginPageAppFolder folder.
        /// </summary>
        [RepositoryFolder("45ae68e9-d80f-47fa-b911-fb57bac99e43")]
        public partial class LoginPageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _maincontentusernameiInfo;
            RepoItemInfo _maincontenttxtpkeyiInfo;
            RepoItemInfo _maincontentbtnokcdInfo;
            RepoItemInfo _loginInfo;
            RepoItemInfo _pnlmainmaincontentclbtsbtnaddsmalliteInfo;
            RepoItemInfo _pnlmainmaincontentclbtsppaddsmallitemInfo;
            RepoItemInfo _pnlmainmaincontentclbtsppaddsmallitem2Info;
            RepoItemInfo _pnlmainmaincontentclbtsppaddsmallitem1Info;
            RepoItemInfo _pnlmainmaincontentclbtsppaddsmallitem3Info;
            RepoItemInfo _pnlmainmaincontentclbtsgrdtimesheetdInfo;
            RepoItemInfo _mainmenumnumaindxi11tInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "/dom[@domain='mortfolio.optiim.com']", parentFolder, 30000, null, false, "45ae68e9-d80f-47fa-b911-fb57bac99e43", "")
            {
                _maincontentusernameiInfo = new RepoItemInfo(this, "MainContentUserNameI", ".//input[#'MainContent_UserName_I']", 30000, null, "b1e84e42-8a40-4310-81d0-7188a73a29ef");
                _maincontenttxtpkeyiInfo = new RepoItemInfo(this, "MainContentTxtPKeyI", ".//input[#'MainContent_txtPKey_I']", 30000, null, "eabbb4b1-70cc-48eb-bbbd-6502486dc21d");
                _maincontentbtnokcdInfo = new RepoItemInfo(this, "MainContentBtnOKCD", ".//div[#'MainContent_btnOK_CD']", 30000, null, "de307dd5-920c-4dc7-aaab-b49db09af344");
                _loginInfo = new RepoItemInfo(this, "Login", ".//div[#'MainContent_btnOK_CD']/span[@innertext='Login']", 30000, null, "979a61ce-7b4c-4353-b85b-33eea4a2e9e5");
                _pnlmainmaincontentclbtsbtnaddsmalliteInfo = new RepoItemInfo(this, "PnlMainMainContentClbTSBtnAddSmallIte", ".//div[#'pnlMain_MainContent_clbTS_btnAddSmallItem_CD']", 30000, null, "97849101-f68d-4418-aeae-5f220745bf19");
                _pnlmainmaincontentclbtsppaddsmallitemInfo = new RepoItemInfo(this, "PnlMainMainContentClbTSPpAddSmallItem", ".//input[#'pnlMain_MainContent_clbTS_ppAddSmallItem_cmbItemType_I']", 30000, null, "c7d2e252-2fc3-4887-95eb-18d85aac952a");
                _pnlmainmaincontentclbtsppaddsmallitem2Info = new RepoItemInfo(this, "PnlMainMainContentClbTSPpAddSmallItem2", ".//input[#'pnlMain_MainContent_clbTS_ppAddSmallItem_cmbItemTypeName_I']", 30000, null, "3b348bf5-7f7b-4df3-927e-63b032cdf637");
                _pnlmainmaincontentclbtsppaddsmallitem1Info = new RepoItemInfo(this, "PnlMainMainContentClbTSPpAddSmallItem1", ".//input[#'pnlMain_MainContent_clbTS_ppAddSmallItem_txtSmallItemDesc_I']", 30000, null, "8dfa1cea-f25b-4970-858c-c33d9ba10362");
                _pnlmainmaincontentclbtsppaddsmallitem3Info = new RepoItemInfo(this, "PnlMainMainContentClbTSPpAddSmallItem3", ".//div[#'pnlMain_MainContent_clbTS_ppAddSmallItem_btnSave_CD']", 30000, null, "5ca8fc2f-0095-4c38-b09c-23305b18bbf9");
                _pnlmainmaincontentclbtsgrdtimesheetdInfo = new RepoItemInfo(this, "PnlMainMainContentClbTSGrdTimeSheetD", ".//img[#'pnlMain_MainContent_clbTS_grdTimeSheet_DXCBtn2Img']", 30000, null, "dacaacda-a1a9-47d4-a910-7e25c1f1f490");
                _mainmenumnumaindxi11tInfo = new RepoItemInfo(this, "MainMenuMnuMainDXI11T", ".//div[#'mainMenu_mnuMain_DXI11_T']", 30000, null, "c19be67d-82fd-4fdd-9df9-24ca942117b6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("45ae68e9-d80f-47fa-b911-fb57bac99e43")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("45ae68e9-d80f-47fa-b911-fb57bac99e43")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MainContentUserNameI item.
            /// </summary>
            [RepositoryItem("b1e84e42-8a40-4310-81d0-7188a73a29ef")]
            public virtual Ranorex.InputTag MainContentUserNameI
            {
                get
                {
                    return _maincontentusernameiInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The MainContentUserNameI item info.
            /// </summary>
            [RepositoryItemInfo("b1e84e42-8a40-4310-81d0-7188a73a29ef")]
            public virtual RepoItemInfo MainContentUserNameIInfo
            {
                get
                {
                    return _maincontentusernameiInfo;
                }
            }

            /// <summary>
            /// The MainContentTxtPKeyI item.
            /// </summary>
            [RepositoryItem("eabbb4b1-70cc-48eb-bbbd-6502486dc21d")]
            public virtual Ranorex.InputTag MainContentTxtPKeyI
            {
                get
                {
                    return _maincontenttxtpkeyiInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The MainContentTxtPKeyI item info.
            /// </summary>
            [RepositoryItemInfo("eabbb4b1-70cc-48eb-bbbd-6502486dc21d")]
            public virtual RepoItemInfo MainContentTxtPKeyIInfo
            {
                get
                {
                    return _maincontenttxtpkeyiInfo;
                }
            }

            /// <summary>
            /// The MainContentBtnOKCD item.
            /// </summary>
            [RepositoryItem("de307dd5-920c-4dc7-aaab-b49db09af344")]
            public virtual Ranorex.DivTag MainContentBtnOKCD
            {
                get
                {
                    return _maincontentbtnokcdInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MainContentBtnOKCD item info.
            /// </summary>
            [RepositoryItemInfo("de307dd5-920c-4dc7-aaab-b49db09af344")]
            public virtual RepoItemInfo MainContentBtnOKCDInfo
            {
                get
                {
                    return _maincontentbtnokcdInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("979a61ce-7b4c-4353-b85b-33eea4a2e9e5")]
            public virtual Ranorex.SpanTag Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("979a61ce-7b4c-4353-b85b-33eea4a2e9e5")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The PnlMainMainContentClbTSBtnAddSmallIte item.
            /// </summary>
            [RepositoryItem("97849101-f68d-4418-aeae-5f220745bf19")]
            public virtual Ranorex.DivTag PnlMainMainContentClbTSBtnAddSmallIte
            {
                get
                {
                    return _pnlmainmaincontentclbtsbtnaddsmalliteInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PnlMainMainContentClbTSBtnAddSmallIte item info.
            /// </summary>
            [RepositoryItemInfo("97849101-f68d-4418-aeae-5f220745bf19")]
            public virtual RepoItemInfo PnlMainMainContentClbTSBtnAddSmallIteInfo
            {
                get
                {
                    return _pnlmainmaincontentclbtsbtnaddsmalliteInfo;
                }
            }

            /// <summary>
            /// The PnlMainMainContentClbTSPpAddSmallItem item.
            /// </summary>
            [RepositoryItem("c7d2e252-2fc3-4887-95eb-18d85aac952a")]
            public virtual Ranorex.InputTag PnlMainMainContentClbTSPpAddSmallItem
            {
                get
                {
                    return _pnlmainmaincontentclbtsppaddsmallitemInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PnlMainMainContentClbTSPpAddSmallItem item info.
            /// </summary>
            [RepositoryItemInfo("c7d2e252-2fc3-4887-95eb-18d85aac952a")]
            public virtual RepoItemInfo PnlMainMainContentClbTSPpAddSmallItemInfo
            {
                get
                {
                    return _pnlmainmaincontentclbtsppaddsmallitemInfo;
                }
            }

            /// <summary>
            /// The PnlMainMainContentClbTSPpAddSmallItem2 item.
            /// </summary>
            [RepositoryItem("3b348bf5-7f7b-4df3-927e-63b032cdf637")]
            public virtual Ranorex.InputTag PnlMainMainContentClbTSPpAddSmallItem2
            {
                get
                {
                    return _pnlmainmaincontentclbtsppaddsmallitem2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PnlMainMainContentClbTSPpAddSmallItem2 item info.
            /// </summary>
            [RepositoryItemInfo("3b348bf5-7f7b-4df3-927e-63b032cdf637")]
            public virtual RepoItemInfo PnlMainMainContentClbTSPpAddSmallItem2Info
            {
                get
                {
                    return _pnlmainmaincontentclbtsppaddsmallitem2Info;
                }
            }

            /// <summary>
            /// The PnlMainMainContentClbTSPpAddSmallItem1 item.
            /// </summary>
            [RepositoryItem("8dfa1cea-f25b-4970-858c-c33d9ba10362")]
            public virtual Ranorex.InputTag PnlMainMainContentClbTSPpAddSmallItem1
            {
                get
                {
                    return _pnlmainmaincontentclbtsppaddsmallitem1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PnlMainMainContentClbTSPpAddSmallItem1 item info.
            /// </summary>
            [RepositoryItemInfo("8dfa1cea-f25b-4970-858c-c33d9ba10362")]
            public virtual RepoItemInfo PnlMainMainContentClbTSPpAddSmallItem1Info
            {
                get
                {
                    return _pnlmainmaincontentclbtsppaddsmallitem1Info;
                }
            }

            /// <summary>
            /// The PnlMainMainContentClbTSPpAddSmallItem3 item.
            /// </summary>
            [RepositoryItem("5ca8fc2f-0095-4c38-b09c-23305b18bbf9")]
            public virtual Ranorex.DivTag PnlMainMainContentClbTSPpAddSmallItem3
            {
                get
                {
                    return _pnlmainmaincontentclbtsppaddsmallitem3Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PnlMainMainContentClbTSPpAddSmallItem3 item info.
            /// </summary>
            [RepositoryItemInfo("5ca8fc2f-0095-4c38-b09c-23305b18bbf9")]
            public virtual RepoItemInfo PnlMainMainContentClbTSPpAddSmallItem3Info
            {
                get
                {
                    return _pnlmainmaincontentclbtsppaddsmallitem3Info;
                }
            }

            /// <summary>
            /// The PnlMainMainContentClbTSGrdTimeSheetD item.
            /// </summary>
            [RepositoryItem("dacaacda-a1a9-47d4-a910-7e25c1f1f490")]
            public virtual Ranorex.ImgTag PnlMainMainContentClbTSGrdTimeSheetD
            {
                get
                {
                    return _pnlmainmaincontentclbtsgrdtimesheetdInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The PnlMainMainContentClbTSGrdTimeSheetD item info.
            /// </summary>
            [RepositoryItemInfo("dacaacda-a1a9-47d4-a910-7e25c1f1f490")]
            public virtual RepoItemInfo PnlMainMainContentClbTSGrdTimeSheetDInfo
            {
                get
                {
                    return _pnlmainmaincontentclbtsgrdtimesheetdInfo;
                }
            }

            /// <summary>
            /// The MainMenuMnuMainDXI11T item.
            /// </summary>
            [RepositoryItem("c19be67d-82fd-4fdd-9df9-24ca942117b6")]
            public virtual Ranorex.DivTag MainMenuMnuMainDXI11T
            {
                get
                {
                    return _mainmenumnumaindxi11tInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MainMenuMnuMainDXI11T item info.
            /// </summary>
            [RepositoryItemInfo("c19be67d-82fd-4fdd-9df9-24ca942117b6")]
            public virtual RepoItemInfo MainMenuMnuMainDXI11TInfo
            {
                get
                {
                    return _mainmenumnumaindxi11tInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}